# Site settings
title: "StatLore"
# email: myemail@gmail.com
description: "Quick statistics reference"
google_analytics: G-RJBL4JRZQ8

plugins:
  # search engine optimization
  - jekyll-seo-tag
  # create sitemap
  - jekyll-sitemap

# Build settings
markdown: kramdown
permalink: /:title

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      comments: true

# To include special collections:
#   create a dir called _mycollections, and put things there
# You can replace `mycollections` with anything
# http://jekyllrb.com/docs/collections/
# NOTE: Uncomment below 
#
# collections:
#   mycollection:
#     output: true
#     permalink: /mycollection/:title/
